"""
filter_evimo_objects.py

Reads EVIMO raw sequences (already preprocessed by preprocess_evimo.py) and
produces a filtered copy where events generated by moving objects have been
removed using their Vicon-tracked 6DOF poses.

How it works:
  1. Parse config.txt  → which Object_N are moving
  2. Parse extrinsics.txt → camera-to-tracker rigid transform + object half-sizes
  3. Extract camera and moving-object Vicon poses from the bag
  4. Build a (H,W) binary mask at each Vicon sample (~100 Hz):
       - project the 4 corners of the planar target into distorted image space
       - fill the convex quad + apply a margin dilation
       - union masks for all moving objects
  5. For every event (ts, x, y, p): look up the nearest-in-time mask.
     Discard the event if it falls inside the mask.
  6. Save filtered evs.npy + copy all other files to the output directory.

Usage:
    python scripts/filter_evimo_objects.py \\
        --datapath /home/i/i0002573/datasets/evimo/eval \\
        --outpath  /home/i/i0002573/datasets/evimo_filtered_2805/eval

    # dry-run (no disk write):
    python scripts/filter_evimo_objects.py \\
        --datapath /home/i/i0002573/datasets/evimo/eval \\
        --outpath  /tmp/evimo_dry \\
        --dry_run
"""

import os
import glob
import shutil
import argparse
import struct

import numpy as np
import cv2
from scipy.spatial.transform import Rotation, Slerp
from scipy.interpolate import interp1d

from rosbags.rosbag1 import Reader
from rosbags.typesys import Stores, get_typestore, get_types_from_msg


H, W = 260, 346   # DVS346 sensor resolution
MARGIN_PX = 10    # dilation margin applied to each projected mask (pixels)


# ---------------------------------------------------------------------------
# Parsing helpers
# ---------------------------------------------------------------------------

def parse_config(config_path):
    """Return set of 1-based object indices that are moving (value == 'true')."""
    moving = set()
    with open(config_path) as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            key, val = line.split(":")
            key = key.strip()   # "Object1", "Object2", …
            val = val.strip().lower()
            if val == "true":
                idx = int(key.replace("Object", ""))
                moving.add(idx)
    return moving


def parse_extrinsics(extrinsics_path):
    """
    extrinsics.txt layout (EVIMO raw format):
      line 1: tx ty tz rx ry rz  (Rodrigues, not used)
      line 2: tx ty tz qx qy qz qw  → camera-to-tracker rigid transform
      line 3: half_x  (object half-width, metres)
      line 4: half_y  (object half-height, metres)

    Returns:
      t_E : (3,) translation  [camera→tracker]
      R_E : (3,3) rotation    [camera→tracker]
      half_x, half_y : float
    """
    lines = open(extrinsics_path).read().split()
    # line 2 starts at index 6 (after 6 values on line 1)
    tx, ty, tz = float(lines[6]), float(lines[7]), float(lines[8])
    # File stores [w, x, y, z]; scipy Rotation.from_quat expects [x, y, z, w]
    qw, qx, qy, qz = float(lines[9]), float(lines[10]), float(lines[11]), float(lines[12])
    t_E = np.array([tx, ty, tz])
    R_E = Rotation.from_quat([qx, qy, qz, qw]).as_matrix()
    half_x = float(lines[13])
    half_y = float(lines[14])
    return t_E, R_E, half_x, half_y


def load_calib(calib_path):
    """
    calib.txt: fx fy cx cy [k1 k2 p1 p2 [k3]]
    Returns K (3x3), dist (4 or 5,).
    """
    vals = np.loadtxt(calib_path)
    fx, fy, cx, cy = vals[:4]
    dist = vals[4:]
    K = np.array([[fx, 0, cx], [0, fy, cy], [0, 0, 1]], dtype=np.float64)
    return K, dist.astype(np.float64)


# ---------------------------------------------------------------------------
# Bag extraction
# ---------------------------------------------------------------------------

def _load_typestore(bagpath):
    typestore = get_typestore(Stores.ROS1_NOETIC)
    with Reader(bagpath) as r:
        add = {}
        for conn in r.connections:
            fmt, msgdef = conn.msgdef
            add.update(get_types_from_msg(msgdef, conn.msgtype))
        typestore.register(add)
    return typestore


def extract_vicon_poses(bagpath, topic, typestore):
    """
    Read all non-occluded Vicon poses for `topic`.
    Returns (tss_us, positions (N,3), quats_xyzw (N,4)).
    """
    tss, pos, quat = [], [], []
    with Reader(bagpath) as r:
        conns = [c for c in r.connections if c.topic == topic]
        for conn, _, raw in r.messages(connections=conns):
            msg = typestore.deserialize_ros1(raw, conn.msgtype)
            if msg.occluded:
                continue
            ts = msg.header.stamp.sec * 1e6 + msg.header.stamp.nanosec / 1e3
            p, q = msg.position, msg.orientation
            tss.append(ts)
            pos.append([p.x, p.y, p.z])
            quat.append([q.x, q.y, q.z, q.w])
    if not tss:
        return None, None, None
    order = np.argsort(tss)
    return (np.array(tss)[order],
            np.array(pos)[order],
            np.array(quat)[order])


# ---------------------------------------------------------------------------
# Pose interpolation
# ---------------------------------------------------------------------------

def make_pose_interpolator(tss_us, positions, quats_xyzw):
    """
    Returns a callable interp(t_us) → (pos (3,), R (3,3)).
    Uses linear interpolation for translation, SLERP for rotation.
    """
    rotations = Rotation.from_quat(quats_xyzw)
    slerp = Slerp(tss_us, rotations)
    trans_interp = interp1d(tss_us, positions, axis=0,
                            kind='linear', bounds_error=False,
                            fill_value=(positions[0], positions[-1]))

    def interp(t_us):
        t_clipped = np.clip(t_us, tss_us[0], tss_us[-1])
        pos = trans_interp(t_clipped)
        rot = slerp(t_clipped).as_matrix()
        return pos, rot

    return interp


# ---------------------------------------------------------------------------
# Mask building
# ---------------------------------------------------------------------------

def _compose_transform(V_pos, V_R, t_E, R_E):
    """
    Camera pose in world: T_world←cam = T_world←tracker × T_tracker←cam^{-1}
    Equivalently, using T_cam←tracker (i.e. E^{-1}):
        T_world←cam: R = V_R × R_E,   t = V_R × t_E + V_pos
    Returns (t_cam_world (3,), R_cam_world (3,3)).
    """
    R_cam = V_R @ R_E
    t_cam = V_R @ t_E + V_pos
    return t_cam, R_cam


def _project_object_mask(t_cam_w, R_cam_w, obj_pos, obj_R,
                          half_x, half_y, K, dist, margin_px):
    """
    Projects the 4 corners of the planar object (±half_x, ±half_y, 0) into
    the distorted image plane.  Returns a (H,W) uint8 mask (255 = object),
    or None if the object is behind the camera.
    """
    # Object corners in object frame
    corners_obj = np.array([
        [ half_x,  half_y, 0.0],
        [ half_x, -half_y, 0.0],
        [-half_x, -half_y, 0.0],
        [-half_x,  half_y, 0.0],
    ])  # (4,3)

    # Transform corners: object → world → camera
    corners_world = (obj_R @ corners_obj.T).T + obj_pos       # (4,3)
    R_world_to_cam = R_cam_w.T
    corners_cam = (R_world_to_cam @ (corners_world - t_cam_w).T).T  # (4,3)

    # Skip if any corner is at or behind the image plane
    if np.any(corners_cam[:, 2] <= 0.0):
        return None

    # Project to distorted image using OpenCV
    rvec = np.zeros(3)
    tvec = np.zeros(3)
    pts_2d, _ = cv2.projectPoints(
        corners_cam.reshape(-1, 1, 3).astype(np.float64),
        rvec, tvec, K, dist)
    pts_2d = pts_2d.reshape(-1, 2).astype(np.float32)

    # Skip if projected polygon is entirely outside the image
    xmin, xmax = pts_2d[:, 0].min(), pts_2d[:, 0].max()
    ymin, ymax = pts_2d[:, 1].min(), pts_2d[:, 1].max()
    if xmax < 0 or xmin >= W or ymax < 0 or ymin >= H:
        return None

    mask = np.zeros((H, W), dtype=np.uint8)
    cv2.fillPoly(mask, [pts_2d.astype(np.int32)], 255)

    if margin_px > 0:
        kernel = cv2.getStructuringElement(
            cv2.MORPH_ELLIPSE, (2 * margin_px + 1, 2 * margin_px + 1))
        mask = cv2.dilate(mask, kernel)

    return mask


def build_mask_stack(cam_interp, obj_interps, moving_ids,
                      t_E, R_E, half_x, half_y, K, dist,
                      vicon_tss):
    """
    Build a (N_T, H, W) uint8 mask stack, one frame per Vicon timestamp.
    mask_stack[i] = 255 where any moving object is present at vicon_tss[i].
    """
    N_T = len(vicon_tss)
    mask_stack = np.zeros((N_T, H, W), dtype=np.uint8)

    for i, t in enumerate(vicon_tss):
        cam_pos, cam_R = cam_interp(t)
        t_cam_w, R_cam_w = _compose_transform(cam_pos, cam_R, t_E, R_E)

        for obj_id in moving_ids:
            if obj_id not in obj_interps:
                continue
            obj_pos, obj_R = obj_interps[obj_id](t)
            m = _project_object_mask(t_cam_w, R_cam_w, obj_pos, obj_R,
                                      half_x, half_y, K, dist, MARGIN_PX)
            if m is not None:
                mask_stack[i] = np.maximum(mask_stack[i], m)

    return mask_stack


# ---------------------------------------------------------------------------
# Event filtering
# ---------------------------------------------------------------------------

def filter_events(evs, mask_stack, vicon_tss):
    """
    evs : (N,4) float64 — [ts_us, x, y, p]
    mask_stack : (N_T, H, W) uint8 — 255 where object is
    vicon_tss  : (N_T,) float64

    Returns filtered evs (M,4) with events inside any mask removed.
    """
    ev_tss = evs[:, 0]
    ev_x   = evs[:, 1].astype(np.int32).clip(0, W - 1)
    ev_y   = evs[:, 2].astype(np.int32).clip(0, H - 1)

    # For each event, find the nearest Vicon timestamp index
    idx = np.searchsorted(vicon_tss, ev_tss)        # index of first vicon_t >= ev_t
    idx = idx.clip(0, len(vicon_tss) - 1)
    left  = (idx - 1).clip(0, len(vicon_tss) - 1)
    right = idx
    nearest = np.where(
        np.abs(ev_tss - vicon_tss[left]) <= np.abs(ev_tss - vicon_tss[right]),
        left, right)

    # Vectorised mask lookup
    is_masked = mask_stack[nearest, ev_y, ev_x] > 0   # (N,) bool

    return evs[~is_masked], is_masked.sum()


# ---------------------------------------------------------------------------
# Per-sequence processing
# ---------------------------------------------------------------------------

def process_sequence(seqdir, out_seqdir, typestore, dry_run=False):
    bagfiles = glob.glob(os.path.join(seqdir, "*.bag"))
    if not bagfiles:
        print(f"  [skip] no bag in {seqdir}")
        return {}

    bagpath   = bagfiles[0]
    cfg_path  = os.path.join(seqdir, "config.txt")
    ext_path  = os.path.join(seqdir, "extrinsics.txt")
    cal_path  = os.path.join(seqdir, "calib.txt")
    evs_path  = os.path.join(seqdir, "evs.npy")

    for p in [cfg_path, ext_path, cal_path, evs_path]:
        if not os.path.exists(p):
            print(f"  [skip] missing {os.path.basename(p)}")
            return {}

    # --- Parse metadata ---
    moving_ids = parse_config(cfg_path)
    if not moving_ids:
        print(f"  [skip] no moving objects declared in config.txt")
        return {}

    t_E, R_E, half_x, half_y = parse_extrinsics(ext_path)
    K, dist = load_calib(cal_path)

    print(f"  Moving objects: {sorted(moving_ids)}, half-size: {half_x:.4f}×{half_y:.4f} m")

    # --- Extract poses from bag ---
    cam_tss, cam_pos, cam_quat = extract_vicon_poses(bagpath, '/vicon/DVS346', typestore)
    if cam_tss is None:
        print("  [skip] no camera poses found")
        return {}
    cam_interp = make_pose_interpolator(cam_tss, cam_pos, cam_quat)

    obj_interps = {}
    for obj_id in moving_ids:
        topic = f'/vicon/Object_{obj_id}'
        tss, pos, quat = extract_vicon_poses(bagpath, topic, typestore)
        if tss is None:
            print(f"  [warn] no poses for {topic}, skipping object {obj_id}")
            continue
        obj_interps[obj_id] = make_pose_interpolator(tss, pos, quat)

    if not obj_interps:
        print("  [skip] no usable moving object poses")
        return {}

    # --- Build mask stack at Vicon frequency (camera tss) ---
    print(f"  Building mask stack ({len(cam_tss)} frames)…", end=" ", flush=True)
    mask_stack = build_mask_stack(
        cam_interp, obj_interps, set(obj_interps.keys()),
        t_E, R_E, half_x, half_y, K, dist, cam_tss)
    coverage = (mask_stack > 0).mean() * 100
    print(f"done. Avg mask coverage: {coverage:.1f}%")

    # --- Filter events ---
    evs = np.load(evs_path)
    n_before = len(evs)
    evs_filtered, n_removed = filter_events(evs, mask_stack, cam_tss)
    n_after = len(evs_filtered)
    pct = 100 * n_removed / n_before if n_before > 0 else 0
    print(f"  Events: {n_before:,} → {n_after:,} (removed {n_removed:,} = {pct:.1f}%)")

    stats = {
        "n_before": int(n_before),
        "n_after": int(n_after),
        "n_removed": int(n_removed),
        "pct_removed": float(pct),
        "mask_coverage_pct": float(coverage),
        "moving_objects": sorted(moving_ids),
    }

    if dry_run:
        return stats

    # --- Write output ---
    os.makedirs(out_seqdir, exist_ok=True)

    # Copy all files except evs.npy (we replace it)
    skip = {"evs.npy"}
    for fname in os.listdir(seqdir):
        if fname in skip:
            continue
        src = os.path.join(seqdir, fname)
        dst = os.path.join(out_seqdir, fname)
        if os.path.isfile(src):
            shutil.copy2(src, dst)

    # Save filtered events
    out_evs = os.path.join(out_seqdir, "evs.npy")
    np.save(out_evs, evs_filtered)
    print(f"  Saved → {out_evs}")

    return stats


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--datapath", required=True,
                        help="Path to EVIMO eval/ directory (source)")
    parser.add_argument("--outpath", required=True,
                        help="Path to output directory")
    parser.add_argument("--dry_run", action="store_true",
                        help="Compute stats without writing files")
    args = parser.parse_args()

    seqdirs = sorted(glob.glob(os.path.join(args.datapath, "*/raw/seq_*")))
    if not seqdirs:
        print(f"No sequences found under {args.datapath}")
        return

    print(f"Found {len(seqdirs)} sequences under {args.datapath}")
    if args.dry_run:
        print("[DRY RUN — no files will be written]")

    # Build typestore once from first bag (all bags share the same message types)
    first_bag = glob.glob(os.path.join(seqdirs[0], "*.bag"))[0]
    typestore = _load_typestore(first_bag)

    all_stats = {}
    total_removed = 0
    total_before  = 0

    for seqdir in seqdirs:
        rel = os.path.relpath(seqdir, args.datapath)
        out_seqdir = os.path.join(args.outpath, rel)
        print(f"\n── {rel}")
        stats = process_sequence(seqdir, out_seqdir, typestore, dry_run=args.dry_run)
        if stats:
            all_stats[rel] = stats
            total_before  += stats["n_before"]
            total_removed += stats["n_removed"]

    # Summary
    print("\n" + "="*60)
    print("SUMMARY")
    print("="*60)
    for rel, s in sorted(all_stats.items()):
        print(f"  {rel:<35} {s['n_removed']:>8,} removed "
              f"({s['pct_removed']:5.1f}%)  coverage {s['mask_coverage_pct']:4.1f}%")
    if total_before > 0:
        print(f"\n  TOTAL: {total_removed:,} / {total_before:,} events removed "
              f"({100*total_removed/total_before:.1f}%)")

    # Save stats JSON
    if not args.dry_run:
        import json
        os.makedirs(args.outpath, exist_ok=True)
        stats_path = os.path.join(args.outpath, "filter_stats.json")
        with open(stats_path, "w") as f:
            json.dump(all_stats, f, indent=2)
        print(f"\nStats saved → {stats_path}")

    print("\nDone.")


if __name__ == "__main__":
    main()
